### ISSUE TITLE
examples中的qmix_sc2.py运行报错问题

### ISSUE THREAD

**Issue by ywk4432** [agi-brain/xuance#13]
运行qmix_sc2.py时报错：
Traceback (most recent call last):
  File "qmix_sc2.py", line 377, in <module>
    runner = Runner(args)
  File "qmix_sc2.py", line 70, in __init__
    self.envs = make_envs(args)
  File "/home/ustc-lc1/miniconda3/envs/env_ywk/lib/python3.7/site-packages/xuance/environment/__init__.py", line 66, in make_envs
    raise NotImplementedError
NotImplementedError

**Comment by wenzhangliu** [comment]
你好，出现这个报错，是因为qmix是近期才上传到GitHub上的，尚未上传PyPI平台，所以您用"pip install xuance"指令安装的xuance版本暂时不支持。

针对这个问题，我们刚刚已经在PyPI上传了最新版的xuance，和目前GitHub上的同步了。

由于xuance会持续开发，更新，如前所述，GitHub上的时效性是最高的，我们一般在成功开发出新功能之后立刻上传至GitHub，等一些功能测试稳定后再统一上传至PyPI。

因此，如果您想保持跟进最新版的xuance，我们建议您下载GitHub上的工程文件，直接在该工程文件里运行demo也可以。

**Comment by ywk4432** [comment]
非常感谢您的回复。非常期待xaunce的持续开发工作。
