### ISSUE TITLE
测试用例出现问题

### ISSUE THREAD

**Issue by HawkQ** [agi-brain/xuance#27]
运行测试用例
```
import xuance
runner = xuance.get_runner(method='dqn',
                           env='classic_control',
                           env_id='CartPole-v1',
                           is_test=False)
runner.run()
```
正常完成训练，但将`is_test`改为`True`后运行，则报错：
```
Traceback (most recent call last):
  File "E:\Reinforcement Learning\xuance\cartpole.py", line 7, in <module>
    runner.run()
  File "D:\Anaconda\envs\xuance\lib\site-packages\xuance\torch\runners\runner_drl.py", line 85, in run
    self.agent.load_model(self.agent.model_dir_load, self.args.seed)
  File "D:\Anaconda\envs\xuance\lib\site-packages\xuance\torch\agents\agent.py", line 93, in load_model
    self.learner.load_model(path, seed)
  File "D:\Anaconda\envs\xuance\lib\site-packages\xuance\torch\learners\learner.py", line 38, in load_model
    model_path = os.path.join(path, model_names[-1])
IndexError: list index out of range
```
环境：windows 10，xuance 1.0.10，torch 1.13.0+cu117
辛苦各位解答！

**Comment by wenzhangliu** [comment]
你好，请检查一下训练完毕后，主目录下是否有/models和/logs两个文件夹？如果有的话，请检查/models下的文件夹是否保存有模型文件？
