### ISSUE TITLE
How to use the dict type observation

### ISSUE THREAD

**Issue by WangJuan6** [agi-brain/xuance#45]
Hi,
I want to use the custom environment, I created a new environment following the steps in the [document](https://xuance.readthedocs.io/en/latest/documents/api/environments/new_env.html), the observation is defined as Dict type, but I got an error:
```
Traceback (most recent call last):
  File "/data/projects/20240628/xuance/procthor_ppo.py", line 18, in <module>
    runner = get_runner(method=parser.method,
  File "/data/projects/20240628/xuance/xuance/common/common_tools.py", line 243, in get_runner
    runner = REGISTRY_Runner[args.runner](args)
  File "/data/projects/20240628/xuance/xuance/torch/runners/runner_drl.py", line 27, in __init__
    self.agent = REGISTRY_Agents[self.config.agent](self.config, self.envs)
  File "/data/projects/20240628/xuance/xuance/torch/agents/policy_gradient/ppoclip_agent.py", line 32, in __init__
    self.policy = self._build_policy()
  File "/data/projects/20240628/xuance/xuance/torch/agents/policy_gradient/ppoclip_agent.py", line 60, in _build_policy
    representation = self._build_representation(self.config.representation, self.config)
  File "/data/projects/20240628/xuance/xuance/torch/agents/agent.py", line 192, in _build_representation
    representation = REGISTRY_Representation["Basic_MLP"](
  File "/data/projects/20240628/xuance/xuance/torch/representations/mlp.py", line 41, in __init__
    self.model = self._create_network()
  File "/data/projects/20240628/xuance/xuance/torch/representations/mlp.py", line 47, in _create_network
    mlp, input_shape = mlp_block(input_shape[0], h, self.normalize, self.activation, self.initialize,
KeyError: 0
```
The value of the input_shape is:`{'rgb': (3, 480, 640), 'semantic': (3, 480, 640)}` and the error shows that the network can not parse input_shape correctly.
Can you help me to solve this problem?
Thanks

**Comment by wenzhangliu** [comment]
The documents for customized environments are updated and removed to [https://xuance.readthedocs.io/en/latest/documents/usage/new_envs.html.](https://xuance.readthedocs.io/en/latest/documents/usage/new_envs.html.). You can try your customized envs with the newest version of XuanCe (v1.2.1).

**Comment by WangJuan6** [comment]
OK, thanks for your reply.
